# Generated by Django 3.2 on 2021-04-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('cost', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('trading_code', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checkedin', 'Checked in'), ('completed', 'Completed'), ('pending', 'Pending'), ('cancel', 'Cancel')], default='pending', max_length=12)),
                ('room_number', models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.room')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reserv', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='booking.reservation')),
                ('title', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=1)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checked in', 'Checked in'), ('checked out', 'Checked out'), ('confirmed', 'Confirmed'), ('cancel', 'Cancel')], max_length=11)),
                ('reserved', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.reservation')),
                ('room_number', models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.room')),
            ],
            options={
                'db_table': 'reservation_detail',
            },
        ),
    ]
