# Generated by Django 3.2 on 2021-05-18 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_number',
            field=models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationdetail',
            name='reserved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationdetail',
            name='room_number',
            field=models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
