# Generated by Django 3.2 on 2021-04-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('manager_id', models.IntegerField(db_column='managerID')),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('num_person', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('family', 'Family')], max_length=10)),
                ('area', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('using', 'Using'), ('not clean', 'Need Clean'), ('broken', 'Broken')], default='available', max_length=32)),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.roomtype')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.roomtype')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
